# https://github.com/elastic/elasticsearch-docker
FROM registry.cn-hangzhou.aliyuncs.com/leoliew/elasticsearch

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
