# https://github.com/elastic/logstash-docker
FROM registry.cn-hangzhou.aliyuncs.com/leoliew/logstash

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
